### ISSUE TITLE
String index out of range

### ISSUE THREAD

**Issue by GustavoRPS** [coinbase/coinbase-java#20]
```
 java.lang.StringIndexOutOfBoundsException: String index out of range: -1
! at java.lang.String.substring(String.java:1871) ~[na:1.7.0_75]
! at org.whispersystems.bithub.storage.CoinbaseTransactionParser.parseUrlFromMessage(CoinbaseTransactionParser.java:55) ~[BitHub-0.1.jar:0.1]
```

```java
  public String parseUrlFromMessage() throws ParseException {
    String message = StringEscapeUtils.unescapeHtml4(coinbaseTransaction.getNotes());
    int urlIndex = message.indexOf("https://");

    return message.substring(urlIndex).trim(); // this line
  }
```

**Comment by GustavoRPS** [comment]
Excuse my lack of attention, the problem is not that library.
