### ISSUE TITLE
Scopes don't match current API version.

### ISSUE THREAD

**Issue by yeikel** [coinbase/coinbase-java#58]
Hi is this library usable? 

I have a very simple configuration : 

```
final String COINBASE_API_KEY = ""******";";
final String COINBASE_API_SECRET = "******";
Coinbase cb = new CoinbaseBuilder().withApiKey(COINBASE_API_KEY,COINBASE_API_SECRET).build();
cb.getAccounts();

```

Which results on 
```
Exception in thread "main" com.coinbase.api.exception.CoinbaseException: Scopes don't match current API version.
	at com.coinbase.api.CoinbaseImpl.handleErrors(CoinbaseImpl.java:1330)
	at com.coinbase.api.CoinbaseImpl.doHttp(CoinbaseImpl.java:1276)
	at com.coinbase.api.CoinbaseImpl.get(CoinbaseImpl.java:1303)
	at com.coinbase.api.CoinbaseImpl.getAccounts(CoinbaseImpl.java:182)
	at com.coinbase.api.CoinbaseImpl.getAccounts(CoinbaseImpl.java:154)
	at coinBase.Main.main(Main.java:20)
```

**Comment by sirikumara** [comment]
I am also facing the same issue. Just doing the same code implementation and try to get accounts(). Exception as below
SEVERE: null
com.coinbase.api.exception.CoinbaseException: Scopes don't match current API version.
	at com.coinbase.api.CoinbaseImpl.handleErrors(CoinbaseImpl.java:1330)
	at com.coinbase.api.CoinbaseImpl.doHttp(CoinbaseImpl.java:1276)
	at com.coinbase.api.CoinbaseImpl.get(CoinbaseImpl.java:1303)
	at com.coinbase.api.CoinbaseImpl.getAccounts(CoinbaseImpl.java:182)
	at com.coinbase.api.CoinbaseImpl.getAccounts(CoinbaseImpl.java:154)

Please give some idea to fix the scope issue. 

Thank You 
Sirikumara

**Comment by sirikumara** [comment]
Finally found the solution, When we create API key in the CoinBase API setting page, we can define the API version as V1 or V2. By changing the V1, problem solved.
